# Permalinks
permalink:           pretty

# Setup
title:               Jack Frysinger
tagline:             Jack's first real attempt to build a personal website. Bear with him as he develops his tone and discovers interesting things to write about.
url:                 https://jackfrysinger.com
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jack Frysinger
  url:               https://twitter.com/jackfrys
  email:             jack@jackfrysinger.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist